server:
  port: 80
spring:
  application:
    name: cloud-consumer-order-service
  cloud:
    consul:
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true  # 优先使用服务ip进行注册


