server:
  port: 9528

spring:
  application:
    name: cloudalibaba-sentinel-gateway
  cloud:
    gateway:
      enabled: true
      routes:
        - id: pay_routh1
          uri: http://localhost:9001
          predicates:
            - Path=/nacos/pay/**
    nacos:
      discovery:
        server-addr: localhost:8848
