server:
  port: 2002

spring:
  application:
    name: seata-storage-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  #==========applicationName + druid-mysql8 driver===================
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_storage?characterEncoding=utf8&useSSL=false&serverTimeZone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: root


#==================mybatis====================
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.song.cloud.entities
  configuration:
    map-underscore-to-camel-case: true

#----------------------Seata-------------------
seata:
  registry:
    nacos:
      server-addr: localhost:8848
      namespace: ""
      group: SEATA_GROUP
      application: seata-server
  tx-service-group: default_tx_group   # 事务组，由它获得TC服务的集群名称
  service:
    vgroup-mapping: #点击源码分析
      default_tx_group: default  #事务组与TC服务集群的映射关系
    grouplist:
      default: 127.0.0.1:8091
  data-source-proxy-mode: AT

logging:
  level:
    io:
      seata: info