server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    consul:
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
            maxAge: 3600
      routes:
        - id: pay_routh1  # 路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/get/**   #断言、路径相匹配的进行路由
            - After=2024-04-20T20:51:21.138570300+08:00[Asia/Shanghai]
            - Query=userType,song
#            - My=song
#            - name: My
#              args:
#                userType: song
#            - Cookie=username, xxyy
#            - Method=Get
          filters:
            - AddRequestHeader=X-Request-red, blue
            - RemoveRequestHeader=accept-encoding
            - My=song
        - id: pay_routh2    #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001        #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/info/**   #断言、路径相匹配的进行路由
#      discovery:
#        locator:
#          enabled: true
logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway: trace
