server:
  port: 8001
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/db_cloud_2024?characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&serverTimeZone=GMT%2B8
    username: root
    password: root
  profiles:
    active: dev # 加载开发环境
  #  jackson:
  #    date-format: java.text.SimpleDateFormat
  #    date-format: yyyy-MM-dd HH:mm:ss
  #    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.song.cloud.entities
  configuration:
    map-underscore-to-camel-case: true


#logging:
#  level:
#    web: debug

#management:
#  zipkin:
#    tracing:
#      endpoint: http://127.0.0.1:9411/api/v2/spans
#  tracing:
#    sampling:
#      probability: 1.0  # 采样率默认为0.1(0.1就是10次只能有一次被记录下来)，值越大收集越及时